### ISSUE TITLE
Update crashes

### ISSUE THREAD

**Issue by samo-nz** [miketrewartha/positional#1]
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:225)
	at io.trewartha.positional.ui.position.PositionFragment.onViewCreated(PositionFragment.kt:74)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:146)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:19886)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:911)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:692)
	at android.view.View.measure(View.java:19886)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2328)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1419)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1672)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1307)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6422)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:623)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6378)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

**Comment by miketrewartha** [comment]
Thanks @samo-nz, saw a few of these this morning and it's an easy fix. Fixing it now and I'll push out an update shortly!

**Comment by miketrewartha** [comment]
Alright @samo-nz, this is fixed in v2.8.1. I just released it to the Play Store.

P.S. From one developer to another, thanks for the report and stack trace on GitHub 👍

**Comment by miketrewartha** [comment]
Found another related bug and pushed another build for that one, just FYI. The good version is now live as 2.8.2.
